### PR TITLE
Multiply and transpose now work properly for non squared matrices as well.

### PR DESCRIPTION
**Pull request by sovcharov**
Transpose works for non squared matrices. Changed setData to work with new dimensions and some indexing changed.
Multiply works properly for non squared matrices. Now no additional empty rows added to matrix when multiply non squared matrices.
Please pull.
Thanks.

### CODE REVIEW

**Comment by koggdal** [comment]
Thank you for the contribution! 👍 

Could you also add tests for these things? You can run tests with `./node_modules/.bin/mocha` (I should probably add a script in package.json for this...).

Regarding the slice: I'm trying to minimize object creation for memory reasons, so it would be great if slice was not needed. Maybe you could change `setData` to not go through the whole array if cols and rows are provided?

**Comment by koggdal** [comment]
Added a script for running unit tests now and updated docs.

```
npm run test
```

**Comment by sovcharov** [comment]
Hi. 
Please check my improvements.
Thanks a lot.

**Comment by koggdal** [comment]
Thanks a lot! 👍 It's now published on npm as [2.2.2](https://github.com/koggdal/matrixmath/releases/tag/v2.2.2)

**Pull request merged**
